---
    - name: Get nodejs package
      shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

    - name: Install packages
      become: yes
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items: "{{ packages }}"

    - name: Install remaining packages
      become: yes
      pip:
        name: "{{ item }}"
        state: present
      with_items: "{{ pippackages }}"

    - name: Create target directory
      file: 
        path: /var/lib/jenkins/workspace/templates
        state: directory
        mode: 0755
        owner: jenkins

    - name: Add hibernate.properties
      template:
        src: templates/hibernate.properties.template
        dest: /var/lib/jenkins/workspace/templates/hibernate.properties
        mode: 0644
        owner: jenkins

    - name: setup db.properties
      template:
        src: templates/db.properties.template
        dest: /var/lib/jenkins/workspace/templates/db.properties
        mode: 0644
        owner: jenkins

    - name: setup email.properties
      template:
        src: templates/email.properties.template
        dest: /var/lib/jenkins/workspace/templates/email.properties
        mode: 0644
        owner: jenkins

    - name: Add my.cnf for mysql
      template:
        src: templates/my.cnf
        dest: /root/.my.cnf
        mode: 0644
        owner: jenkins

    - name: Copy pom.xml.orig
      copy:
        src: files/pom.xml.orig
        dest: /var/lib/jenkins/workspace/templates/pom.xml.orig
        mode: 0644
        owner: jenkins

    - name: Copy pom.xml.data
      copy:
        src: files/pom.xml.data
        dest: /var/lib/jenkins/workspace/templates/pom.xml.data
        mode: 0644
        owner: jenkins

    - name: Add mysql user
      mysql_user:
        name: root
        password: "{{ mysql_password }}"
        priv: '*.*:ALL'
        login_user: root
        login_password: "{{ mysql_password }}"
        state: present
      become: yes

    - name: Update root
      raw: mysql -e "UPDATE mysql.user SET Grant_priv='Y', Super_priv='Y' WHERE User='root'; FLUSH PRIVILEGES";

    - name: Add mysql user
      mysql_user:
        name: jenkins
        password: "{{ mysql_password }}"
        priv: '*.*:ALL'
        state: present
      become: yes

    - name: Add jenkins job (iTrust2)
      jenkins_job:
        config: "{{ lookup('file', 'iTrust2.xml') }}"
        name: iTrust2
        password: "{{ jenkins_pass }}"
        url: http://localhost:8008/
        user: admin

    - name: Copy testPrioritization.js
      copy:
        src: testPrioritization.js
        dest: /var/lib/jenkins/workspace/
        mode: 0755
        owner: root

    - name: Copy package.json to install dependencies for testPrioritization.js
      copy:
        src: package.json
        dest: /var/lib/jenkins/workspace/templates/package.json
        mode: 0755
        owner: root
...