---
- hosts: main

  vars:
    mysql_user: jenkins
    mysql_password: "{{ lookup('env','MYSQL_PASS') }}"
    email_username: aapatel8@ncsu.edu
    email_password:
    jenkins_pass: "{{ lookup('env','JENKINS_PASS') }}"
    packages:
      - git
      - default-jdk
      - maven
      - mysql-server-5.7
      - python-mysqldb
      - python-pip
      - python3-lxml

    pippackages:
      - python-jenkins
      - lxml
  
  tasks:
    - name: Install packages
      become: yes
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items: "{{ packages }}"
    
    - name: Install remaining packages
      become: yes
      pip:
        name: "{{ item }}"
        state: present
      with_items: "{{ pippackages }}"

    - name: Create target directory
      file: 
        path: /var/lib/jenkins/workspace/templates
        state: directory
        mode: 0755
        owner: jenkins

    - name: Add hibernate.properties
      template:
        src: templates/hibernate.properties.template
        dest: /var/lib/jenkins/workspace/templates/hibernate.properties
        mode: 0644
        owner: jenkins

    - name: setup db.properties
      template:
        src: templates/db.properties.template
        dest: /var/lib/jenkins/workspace/templates/db.properties
        mode: 0644
        owner: jenkins

    - name: setup email.properties
      template:
        src: templates/email.properties.template
        dest: /var/lib/jenkins/workspace/templates/email.properties
        mode: 0644
        owner: jenkins

    - name: Add my.cnf for mysql
      template:
        src: templates/my.cnf
        dest: /var/lib/jenkins/workspace/templates/my.cnf
        mode: 0644
        owner: jenkins

    - name: Add mysql user
      mysql_user:
        name: root
        password: "{{ mysql_password }}"
        priv: '*.*:ALL'
        login_user: root
        login_password: "{{ mysql_password }}"
        state: present
      become: yes

    - name: Update root
      raw: mysql -e "UPDATE mysql.user SET Grant_priv='Y', Super_priv='Y' WHERE User='root'; FLUSH PRIVILEGES";

    - name: Add mysql user
      mysql_user:
        name: jenkins
        password: "{{ mysql_password }}"
        priv: '*.*:ALL'
        state: present
      become: yes

    - name: Add jenkins job (iTrust2)
      jenkins_job:
        config: "{{ lookup('file', 'iTrust2.xml') }}"
        name: iTrust2
        password: "{{ jenkins_pass }}"
        url: http://localhost:8080/
        user: admin
