#!/bin/bash
export BRANCHNAME=$(git rev-parse --abbrev-ref HEAD)
export MASTER_SHA1=$(git rev-parse master)
export SHA1=$(git rev-parse fuzzer)
export GITHUB_URL=$(git config --get remote.origin.url | sed 's/.git$//')
export JENKINS_IP=159.65.185.67
export JENKINS_PORT=8008

if [ $BRANCHNAME = 'master' ]; then
    node ./.git/scripts/fuzzer.js
elif [ $BRANCHNAME = 'fuzzer' ]; then
    curl "http://$JENKINS_IP:$JENKINS_PORT/git/notifyCommit?url=$GITHUB_URL&branches=fuzzer&sha1=$SHA1"
    echo
fi
